import * as fs from 'fs';
import * as path from 'path';
import { tokenize } from './src/engine/lexer';
import { parse } from './src/engine/parser';
import { instrument } from './src/engine/instrumenter';
import { runCode } from './src/runner/local';

import { SAMPLES } from '../frontend/src/data/samples';
const samples = SAMPLES.filter(s => s.id !== 'blank');

async function exportTraces() {
  const tracesMap: Record<string, any> = {};

  for (const s of samples) {
    console.log(`Generating real trace for: ${s.id}...`);
    const tokens = tokenize(s.code);
    const ast = parse(tokens);
    const inst = instrument(ast, s.code);
    const res = await runCode(inst, s.stdin);
    if (res.exitCode !== 0 || res.stderr || !res.trace.length) throw new Error(`Invalid trace ${s.id}: ${res.stderr}`);
    tracesMap[s.id] = {
      success: true,
      trace: res.trace,
      stdout: res.stdout,
      stepCount: res.trace.length,
      executionTimeMs: res.executionTimeMs,
      isDemo: true,
      sandboxWarning: 'Dữ liệu mô phỏng từ lần chạy C++ thật (Chế độ xem trước GitHub Pages)'
    };
  }

  const outContent = `// Generated by backend/export_demo_traces.ts. Do not edit traces by hand.
import { ExecuteResponse } from '../engine/types';
import { SAMPLES } from './samples';
export const DEMO_TRACES: Record<string, Partial<ExecuteResponse>> = ${JSON.stringify(tracesMap, null, 2)};
export function getFallbackDemoTrace(code: string, stdin: string): Partial<ExecuteResponse> | null {
  const sample = SAMPLES.find(s => s.code === code && s.stdin === stdin);
  return sample ? DEMO_TRACES[sample.id] || null : null;
}
`;

  const destPath = path.resolve(process.cwd(), '../frontend/src/data/demoTraces.ts');
  fs.writeFileSync(destPath, outContent);
  console.log(`Saved demo traces to: ${destPath}`);
}

exportTraces();
