export const ALLOWED_INCLUDES = ['iostream', 'vector', 'algorithm', 'string', 'cmath', 'cstdio', 'cstdlib', 'climits', 'cstring', 'stack', 'queue', 'sstream', 'set', 'map'];

// Build the C++ header as an array of lines to avoid template literal escaping issues
const lines: string[] = [
  '#include <iostream>',
  '#include <string>',
  '#include <vector>',
  '#include <sstream>',
  '#include <cstdio>',
  '#include <cstdlib>',
  '#include <set>',
  '#include <map>',
  '',
  'using namespace std;',
  '',
  'static int __cl_step_count = 0;',
  'static const int __CL_MAX_STEPS = 10000;',
  'static stringstream __cl_cum_stdout;',
  '',
  'struct __cl_CallFrame { string func; int line; string returnValue; int id; string params; };',
  'static vector<__cl_CallFrame> __cl_stack;',
  'static int __cl_frame_id = 0;',
  '',
  'static string __cl_escape(const string& s) {',
  '  string r;',
  '  for (char c : s) {',
  '    switch(c) {',
  String.raw`    case '"': r += "\\\""; break;`,
  String.raw`    case '\\': r += "\\\\"; break;`,
  String.raw`    case '\n': r += "\\n"; break;`,
  String.raw`    case '\r': r += "\\r"; break;`,
  String.raw`    case '\t': r += "\\t"; break;`,
  '    default: r += c;',
  '    }',
  '  }',
  '  return r;',
  '}',
  '',
  'class __cl_StepBuilder {',
  'public:',
  '  int line;',
  '  string event;',
  '  vector<pair<string,string>> vars;',
  '  vector<string> changed;',
  '  string swapInfo;',
  '  string arrayAccess;',
  '  string compareInfo;',
  '  string detail;',
  '',
  '  set<string> uninit_vars;',
  '  map<string, set<int>> init_indices;',
  '',
  '  void set_uninit(const char* name) { uninit_vars.insert(name); init_indices[name].clear(); }',
  '  void set_init(const char* name) { uninit_vars.erase(name); }',
  '  void set_arr_init(const char* name, int idx) { init_indices[name].insert(idx); }',
  '  bool is_uninit(const char* name) { return uninit_vars.count(name) > 0; }',
  '',
  '  void begin(int l, const char* evt) {',
  '    line = l; event = evt; vars.clear(); changed.clear();',
  '    swapInfo = ""; arrayAccess = ""; compareInfo = ""; detail = "";',
  '  }',
  '',
  '  void var_uninit(const char* name) { vars.push_back({name, "null"}); }',
  '  void var_int(const char* name, int val) {',
  '    if (is_uninit(name)) vars.push_back({name, "null"});',
  '    else vars.push_back({name, to_string(val)});',
  '  }',
  '  void var_double(const char* name, double val) {',
  '    if (is_uninit(name)) vars.push_back({name, "null"});',
  '    else vars.push_back({name, to_string(val)});',
  '  }',
  '  void var_char(const char* name, char c) {',
  '    if (is_uninit(name)) vars.push_back({name, "null"});',
  '    else {',
  String.raw`      string s; s += "\""; s += c; s += "\"";`,
  '      vars.push_back({name, s});',
  '    }',
  '  }',
  '  void var_bool(const char* name, bool b) {',
  '    if (is_uninit(name)) vars.push_back({name, "null"});',
  '    else vars.push_back({name, b ? "true" : "false"});',
  '  }',
  '  void var_str(const char* name, const string& s) {',
  '    if (is_uninit(name)) vars.push_back({name, "null"});',
  String.raw`    else vars.push_back({name, "\"" + __cl_escape(s) + "\""});`,
  '  }',
  '',
  '  template<typename T>',
  '  void var_vec(const char* name, const vector<T>& v) {',
  '    if (is_uninit(name)) { vars.push_back({name, "null"}); return; }',
  '    stringstream ss;',
  '    ss << "[";',
  '    for(size_t i = 0; i < v.size(); ++i) {',
  '      if (i > 0) ss << ",";',
  '      ss << v[i];',
  '    }',
  '    ss << "]";',
  '    vars.push_back({name, ss.str()});',
  '  }',
  '',
  '  template<typename T>',
  '  void var_arr(const char* name, T* arr, int sz) {',
  '    stringstream ss;',
  '    ss << "[";',
  '    for(int i = 0; i < sz; ++i) {',
  '      if (i > 0) ss << ",";',
  '      if (is_uninit(name) && init_indices[name].count(i) == 0) ss << "null";',
  '      else ss << arr[i];',
  '    }',
  '    ss << "]";',
  '    vars.push_back({name, ss.str()});',
  '  }',
  '',
  '  void mark_changed(const char* name) { changed.push_back(name); }',
  '  void set_swap(const char* name, int i, int j) {',
  String.raw`    swapInfo = string("{\"name\":\"") + name + "\",\"i\":" + to_string(i) + ",\"j\":" + to_string(j) + "}";`,
  '  }',
  '  template<typename T>',
  '  void set_access(const char* name, int idx, const char* act, T val) {',
  '    stringstream ss;',
  String.raw`    ss << "{\"name\":\"" << name << "\",\"index\":" << idx << ",\"action\":\"" << act << "\",\"value\":" << val << "}";`,
  '    arrayAccess = ss.str();',
  '  }',
  '  void set_compare(const char* left, const char* right, long long lv, long long rv, const char* op, bool res) {',
  String.raw`    compareInfo = string("{\"left\":\"") + __cl_escape(left) + "\",\"right\":\"" + __cl_escape(right) + "\",\"leftValue\":" + to_string(lv) + ",\"rightValue\":" + to_string(rv) + ",\"operator\":\"" + op + "\",\"result\":" + (res ? "true" : "false") + "}";`,
  '  }',
  '  void set_detail(const string& d) {',
  '    detail = __cl_escape(d);',
  '  }',
  '',
  '  template<typename T>',
  '  void set_return(T val) {',
  '    if (!__cl_stack.empty()) {',
  '      stringstream ss;',
  '      ss << val;',
  '      __cl_stack.back().returnValue = ss.str();',
  '    }',
  '  }',
  '  void set_return(bool val) {',
  '    if (!__cl_stack.empty()) __cl_stack.back().returnValue = val ? "true" : "false";',
  '  }',
  '  void set_return(const string& val) {',
  '    if (!__cl_stack.empty()) __cl_stack.back().returnValue = "\"" + __cl_escape(val) + "\"";',
  '  }',
  '',
  '  void emit() {',
  '    string out = "{";',
  String.raw`    out += "\"step\":" + to_string(__cl_step_count) + ",";`,
  String.raw`    out += "\"line\":" + to_string(line) + ",";`,
  String.raw`    out += "\"event\":\"" + event + "\",";`,
  '',
  '    // callStack',
  String.raw`    out += "\"callStack\":[";`,
  '    for (size_t i = 0; i < __cl_stack.size(); ++i) {',
  '      if (i > 0) out += ",";',
  String.raw`      out += "{\"func\":\"" + __cl_stack[i].func + "\",\"line\":" + to_string(__cl_stack[i].line);`,
  String.raw`      out += ",\"id\":" + to_string(__cl_stack[i].id) + ",\"params\":" + __cl_stack[i].params;`,
  '      if (!__cl_stack[i].returnValue.empty()) {',
  String.raw`        out += ",\"returnValue\":" + __cl_stack[i].returnValue;`,
  '      }',
  '      out += "}";',
  '    }',
  '    out += "],";',
  '',
  '    // variables',
  String.raw`    out += "\"variables\":{";`,
  '    for (size_t i = 0; i < vars.size(); ++i) {',
  '      if (i > 0) out += ",";',
  String.raw`      out += "\"" + vars[i].first + "\":" + vars[i].second;`,
  '    }',
  '    out += "},";',
  '',
  '    // changed',
  String.raw`    out += "\"changed\":[";`,
  '    for (size_t i = 0; i < changed.size(); ++i) {',
  '      if (i > 0) out += ",";',
  String.raw`      out += "\"" + changed[i] + "\"";`,
  '    }',
  '    out += "]";',
  '',
  String.raw`    if (!swapInfo.empty()) out += ",\"swapInfo\":" + swapInfo;`,
  String.raw`    if (!arrayAccess.empty()) out += ",\"arrayAccess\":" + arrayAccess;`,
  String.raw`    if (!compareInfo.empty()) out += ",\"compareInfo\":" + compareInfo;`,
  String.raw`    if (!detail.empty()) out += ",\"detail\":\"" + detail + "\"";`,
  String.raw`    out += ",\"stdout\":\"" + __cl_escape(__cl_cum_stdout.str()) + "\"";`,
  '    out += "}";',
  '',
  '    fprintf(stderr, "%s\\n", out.c_str());',
  '    fflush(stderr);',
  '    __cl_step_count++;',
  '  }',
  '};',
  '',
  'static __cl_StepBuilder __cl_sb;',
  '',
  'static void __cl_capture_params() {',
  '  string out = "{";',
  '  for (size_t i = 0; i < __cl_sb.vars.size(); ++i) {',
  '    if (i) out += ",";',
  String.raw`    out += "\"" + __cl_sb.vars[i].first + "\":" + __cl_sb.vars[i].second;`,
  '  }',
  '  __cl_stack.back().params = out + "}";',
  '}',
  'static void __cl_enter(const char* func, int line) {',
  '  __cl_stack.push_back({string(func), line, "", ++__cl_frame_id, "{}"});',
  '}',
  'static void __cl_leave() {',
  '  if (!__cl_stack.empty()) __cl_stack.pop_back();',
  '}',
  '',
  'static void __cl_begin(int line, const char* event) {',
  '  if (__cl_step_count >= __CL_MAX_STEPS) {',
  String.raw`    fprintf(stderr, "{\"error\":\"STEP_LIMIT\"}\n");`,
  '    exit(1);',
  '  }',
  '  __cl_sb.begin(line, event);',
  '}',
  'static void __cl_end() {',
  '  __cl_sb.emit();',
  '}',
  '',
];

export const TRACE_HEADER = lines.join('\n');
