export const ALLOWED_INCLUDES = ['iostream', 'vector', 'algorithm', 'string', 'cmath', 'cstdio', 'cstdlib', 'climits', 'cstring', 'stack', 'queue', 'sstream'];

// Build the C++ header as an array of lines to avoid template literal escaping issues
const lines: string[] = [
  '#include <iostream>',
  '#include <string>',
  '#include <vector>',
  '#include <sstream>',
  '#include <cstdio>',
  '#include <cstdlib>',
  '',
  'using namespace std;',
  '',
  'static int __cl_step_count = 0;',
  'static const int __CL_MAX_STEPS = 10000;',
  'static stringstream __cl_cum_stdout;',
  '',
  'struct __cl_CallFrame { string func; int line; };',
  'static vector<__cl_CallFrame> __cl_stack;',
  '',
  'static string __cl_escape(const string& s) {',
  '  string r;',
  '  for (char c : s) {',
  '    switch(c) {',
  String.raw`    case '"': r += "\\\""; break;`,
  String.raw`    case '\\': r += "\\\\"; break;`,
  String.raw`    case '\n': r += "\\n"; break;`,
  String.raw`    case '\r': r += "\\r"; break;`,
  String.raw`    case '\t': r += "\\t"; break;`,
  '    default: r += c;',
  '    }',
  '  }',
  '  return r;',
  '}',
  '',
  'class __cl_StepBuilder {',
  'public:',
  '  int line;',
  '  string event;',
  '  vector<pair<string,string>> vars;',
  '  vector<string> changed;',
  '  string swapInfo;',
  '  string arrayAccess;',
  '  string compareInfo;',
  '  string detail;',
  '',
  '  void begin(int l, const char* evt) {',
  '    line = l; event = evt; vars.clear(); changed.clear();',
  '    swapInfo = ""; arrayAccess = ""; compareInfo = ""; detail = "";',
  '  }',
  '',
  '  void var_int(const char* name, int val) {',
  '    vars.push_back({name, to_string(val)});',
  '  }',
  '  void var_double(const char* name, double val) {',
  '    vars.push_back({name, to_string(val)});',
  '  }',
  '  void var_char(const char* name, char c) {',
  String.raw`    string s; s += "\""; s += c; s += "\"";`,
  '    vars.push_back({name, s});',
  '  }',
  '  void var_bool(const char* name, bool b) {',
  '    vars.push_back({name, b ? "true" : "false"});',
  '  }',
  '  void var_str(const char* name, const string& s) {',
  String.raw`    vars.push_back({name, "\"" + __cl_escape(s) + "\""});`,
  '  }',
  '',
  '  template<typename T>',
  '  void var_vec(const char* name, const vector<T>& v) {',
  '    stringstream ss;',
  '    ss << "[";',
  '    for(size_t i = 0; i < v.size(); ++i) {',
  '      if (i > 0) ss << ",";',
  '      ss << v[i];',
  '    }',
  '    ss << "]";',
  '    vars.push_back({name, ss.str()});',
  '  }',
  '',
  '  template<typename T>',
  '  void var_arr(const char* name, T* arr, int sz) {',
  '    stringstream ss;',
  '    ss << "[";',
  '    for(int i = 0; i < sz; ++i) {',
  '      if (i > 0) ss << ",";',
  '      ss << arr[i];',
  '    }',
  '    ss << "]";',
  '    vars.push_back({name, ss.str()});',
  '  }',
  '',
  '  void mark_changed(const char* name) { changed.push_back(name); }',
  '  void set_swap(const char* name, int i, int j) {',
  String.raw`    swapInfo = string("{\"name\":\"") + name + "\",\"i\":" + to_string(i) + ",\"j\":" + to_string(j) + "}";`,
  '  }',
  '  void set_access(const char* name, int idx, const char* act) {',
  String.raw`    arrayAccess = string("{\"name\":\"") + name + "\",\"index\":" + to_string(idx) + ",\"action\":\"" + act + "\"}";`,
  '  }',
  '  void set_compare(const char* left, const char* right, long long lv, long long rv, const char* op, bool res) {',
  String.raw`    compareInfo = string("{\"left\":\"") + __cl_escape(left) + "\",\"right\":\"" + __cl_escape(right) + "\",\"leftValue\":" + to_string(lv) + ",\"rightValue\":" + to_string(rv) + ",\"operator\":\"" + op + "\",\"result\":" + (res ? "true" : "false") + "}";`,
  '  }',
  '  void set_detail(const string& d) {',
  '    detail = __cl_escape(d);',
  '  }',
  '',
  '  void emit() {',
  '    string out = "{";',
  String.raw`    out += "\"step\":" + to_string(__cl_step_count) + ",";`,
  String.raw`    out += "\"line\":" + to_string(line) + ",";`,
  String.raw`    out += "\"event\":\"" + event + "\",";`,
  '',
  '    // callStack',
  String.raw`    out += "\"callStack\":[";`,
  '    for (size_t i = 0; i < __cl_stack.size(); ++i) {',
  '      if (i > 0) out += ",";',
  String.raw`      out += "{\"func\":\"" + __cl_stack[i].func + "\",\"line\":" + to_string(__cl_stack[i].line) + "}";`,
  '    }',
  '    out += "],";',
  '',
  '    // variables',
  String.raw`    out += "\"variables\":{";`,
  '    for (size_t i = 0; i < vars.size(); ++i) {',
  '      if (i > 0) out += ",";',
  String.raw`      out += "\"" + vars[i].first + "\":" + vars[i].second;`,
  '    }',
  '    out += "},";',
  '',
  '    // changed',
  String.raw`    out += "\"changed\":[";`,
  '    for (size_t i = 0; i < changed.size(); ++i) {',
  '      if (i > 0) out += ",";',
  String.raw`      out += "\"" + changed[i] + "\"";`,
  '    }',
  '    out += "]";',
  '',
  String.raw`    if (!swapInfo.empty()) out += ",\"swapInfo\":" + swapInfo;`,
  String.raw`    if (!arrayAccess.empty()) out += ",\"arrayAccess\":" + arrayAccess;`,
  String.raw`    if (!compareInfo.empty()) out += ",\"compareInfo\":" + compareInfo;`,
  String.raw`    if (!detail.empty()) out += ",\"detail\":\"" + detail + "\"";`,
  String.raw`    out += ",\"stdout\":\"" + __cl_escape(__cl_cum_stdout.str()) + "\"";`,
  '    out += "}";',
  '',
  '    fprintf(stderr, "%s\\n", out.c_str());',
  '    fflush(stderr);',
  '    __cl_step_count++;',
  '  }',
  '};',
  '',
  'static __cl_StepBuilder __cl_sb;',
  '',
  'static void __cl_enter(const char* func, int line) {',
  '  __cl_stack.push_back({string(func), line});',
  '}',
  'static void __cl_leave() {',
  '  if (!__cl_stack.empty()) __cl_stack.pop_back();',
  '}',
  '',
  'static void __cl_begin(int line, const char* event) {',
  '  if (__cl_step_count >= __CL_MAX_STEPS) {',
  String.raw`    fprintf(stderr, "{\"error\":\"STEP_LIMIT\"}\n");`,
  '    exit(1);',
  '  }',
  '  __cl_sb.begin(line, event);',
  '}',
  'static void __cl_end() {',
  '  __cl_sb.emit();',
  '}',
  '',
];

export const TRACE_HEADER = lines.join('\n');
