// Generated by backend/export_demo_traces.ts. Do not edit traces by hand.
import { ExecuteResponse } from '../engine/types';
import { SAMPLES } from './samples';
export const DEMO_TRACES: Record<string, Partial<ExecuteResponse>> = {
  "array-sum": {
    "success": true,
    "trace": [
      {
        "step": 0,
        "line": 4,
        "event": "call",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {},
        "changed": [],
        "stdout": ""
      },
      {
        "step": 1,
        "line": 5,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": null
        },
        "changed": [
          "n"
        ],
        "stdout": ""
      },
      {
        "step": 2,
        "line": 6,
        "event": "stdin",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5
        },
        "changed": [
          "n"
        ],
        "stdout": ""
      },
      {
        "step": 3,
        "line": 7,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5,
          "arr": [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "stdout": ""
      },
      {
        "step": 4,
        "line": 8,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5,
          "arr": [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 5,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 0,
          "n": 5,
          "arr": [
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 0,
          "mode": "write",
          "value": 1
        },
        "stdout": ""
      },
      {
        "step": 6,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 1,
          "n": 5,
          "arr": [
            1,
            2,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 1,
          "mode": "write",
          "value": 2
        },
        "stdout": ""
      },
      {
        "step": 7,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 2,
          "n": 5,
          "arr": [
            1,
            2,
            3,
            null,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 2,
          "mode": "write",
          "value": 3
        },
        "stdout": ""
      },
      {
        "step": 8,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 3,
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 3,
          "mode": "write",
          "value": 4
        },
        "stdout": ""
      },
      {
        "step": 9,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 4,
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 4,
          "mode": "write",
          "value": 5
        },
        "stdout": ""
      },
      {
        "step": 10,
        "line": 11,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ],
          "sum": 0
        },
        "changed": [
          "sum"
        ],
        "stdout": ""
      },
      {
        "step": 11,
        "line": 12,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ],
          "sum": 0
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 12,
        "line": 13,
        "event": "assign",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 0,
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ],
          "sum": 1
        },
        "changed": [
          "sum"
        ],
        "stdout": ""
      },
      {
        "step": 13,
        "line": 13,
        "event": "assign",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 1,
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ],
          "sum": 3
        },
        "changed": [
          "sum"
        ],
        "stdout": ""
      },
      {
        "step": 14,
        "line": 13,
        "event": "assign",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 2,
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ],
          "sum": 6
        },
        "changed": [
          "sum"
        ],
        "stdout": ""
      },
      {
        "step": 15,
        "line": 13,
        "event": "assign",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 3,
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ],
          "sum": 10
        },
        "changed": [
          "sum"
        ],
        "stdout": ""
      },
      {
        "step": 16,
        "line": 13,
        "event": "assign",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 4,
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ],
          "sum": 15
        },
        "changed": [
          "sum"
        ],
        "stdout": ""
      },
      {
        "step": 17,
        "line": 15,
        "event": "stdout",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ],
          "sum": 15
        },
        "changed": [],
        "stdout": "15\n"
      },
      {
        "step": 18,
        "line": 16,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ],
          "sum": 15
        },
        "changed": [],
        "stdout": "15\n"
      },
      {
        "step": 19,
        "line": 16,
        "event": "return",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {},
            "returnValue": 0
          }
        ],
        "variables": {
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ],
          "sum": 15
        },
        "changed": [],
        "stdout": "15\n"
      }
    ],
    "stdout": "15\n",
    "stepCount": 20,
    "executionTimeMs": 6,
    "isDemo": true,
    "sandboxWarning": "Dữ liệu mô phỏng từ lần chạy C++ thật (Chế độ xem trước GitHub Pages)"
  },
  "binary-search": {
    "success": true,
    "trace": [
      {
        "step": 0,
        "line": 4,
        "event": "call",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {},
        "changed": [],
        "stdout": ""
      },
      {
        "step": 1,
        "line": 5,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": null
        },
        "changed": [
          "n"
        ],
        "stdout": ""
      },
      {
        "step": 2,
        "line": 6,
        "event": "stdin",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 7
        },
        "changed": [
          "n"
        ],
        "stdout": ""
      },
      {
        "step": 3,
        "line": 7,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 7,
          "arr": [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "stdout": ""
      },
      {
        "step": 4,
        "line": 8,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 7,
          "arr": [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 5,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 0,
          "n": 7,
          "arr": [
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 0,
          "mode": "write",
          "value": 1
        },
        "stdout": ""
      },
      {
        "step": 6,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 1,
          "n": 7,
          "arr": [
            1,
            3,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 1,
          "mode": "write",
          "value": 3
        },
        "stdout": ""
      },
      {
        "step": 7,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 2,
          "n": 7,
          "arr": [
            1,
            3,
            5,
            null,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 2,
          "mode": "write",
          "value": 5
        },
        "stdout": ""
      },
      {
        "step": 8,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 3,
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 3,
          "mode": "write",
          "value": 7
        },
        "stdout": ""
      },
      {
        "step": 9,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 4,
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            9,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 4,
          "mode": "write",
          "value": 9
        },
        "stdout": ""
      },
      {
        "step": 10,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 5,
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            9,
            11,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 5,
          "mode": "write",
          "value": 11
        },
        "stdout": ""
      },
      {
        "step": 11,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 6,
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            9,
            11,
            13,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 6,
          "mode": "write",
          "value": 13
        },
        "stdout": ""
      },
      {
        "step": 12,
        "line": 11,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            9,
            11,
            13,
            null,
            null,
            null
          ],
          "target": null
        },
        "changed": [
          "target"
        ],
        "stdout": ""
      },
      {
        "step": 13,
        "line": 12,
        "event": "stdin",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            9,
            11,
            13,
            null,
            null,
            null
          ],
          "target": 7
        },
        "changed": [
          "target"
        ],
        "stdout": ""
      },
      {
        "step": 14,
        "line": 13,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            9,
            11,
            13,
            null,
            null,
            null
          ],
          "target": 7,
          "left": 0
        },
        "changed": [
          "left"
        ],
        "stdout": ""
      },
      {
        "step": 15,
        "line": 13,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            9,
            11,
            13,
            null,
            null,
            null
          ],
          "target": 7,
          "left": 0,
          "right": 6
        },
        "changed": [
          "right"
        ],
        "stdout": ""
      },
      {
        "step": 16,
        "line": 14,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            9,
            11,
            13,
            null,
            null,
            null
          ],
          "target": 7,
          "left": 0,
          "right": 6,
          "result": -1
        },
        "changed": [
          "result"
        ],
        "stdout": ""
      },
      {
        "step": 17,
        "line": 15,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            9,
            11,
            13,
            null,
            null,
            null
          ],
          "target": 7,
          "left": 0,
          "right": 6,
          "result": -1
        },
        "changed": [],
        "compareInfo": {
          "left": "left",
          "right": "right",
          "leftValue": 0,
          "rightValue": 6,
          "operator": "<=",
          "result": true
        },
        "compareAccesses": [],
        "stdout": ""
      },
      {
        "step": 18,
        "line": 16,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "mid": 3,
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            9,
            11,
            13,
            null,
            null,
            null
          ],
          "target": 7,
          "left": 0,
          "right": 6,
          "result": -1
        },
        "changed": [
          "mid"
        ],
        "stdout": ""
      },
      {
        "step": 19,
        "line": 17,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "mid": 3,
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            9,
            11,
            13,
            null,
            null,
            null
          ],
          "target": 7,
          "left": 0,
          "right": 6,
          "result": -1
        },
        "changed": [],
        "compareInfo": {
          "left": "arr[mid]",
          "right": "target",
          "leftValue": 7,
          "rightValue": 7,
          "operator": "==",
          "result": true
        },
        "compareAccesses": [
          {
            "array": "arr",
            "index": 3
          }
        ],
        "stdout": ""
      },
      {
        "step": 20,
        "line": 18,
        "event": "assign",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "mid": 3,
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            9,
            11,
            13,
            null,
            null,
            null
          ],
          "target": 7,
          "left": 0,
          "right": 6,
          "result": 3
        },
        "changed": [
          "result"
        ],
        "stdout": ""
      },
      {
        "step": 21,
        "line": 19,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "mid": 3,
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            9,
            11,
            13,
            null,
            null,
            null
          ],
          "target": 7,
          "left": 0,
          "right": 6,
          "result": 3
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 22,
        "line": 26,
        "event": "stdout",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            9,
            11,
            13,
            null,
            null,
            null
          ],
          "target": 7,
          "left": 0,
          "right": 6,
          "result": 3
        },
        "changed": [],
        "stdout": "3\n"
      },
      {
        "step": 23,
        "line": 27,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            9,
            11,
            13,
            null,
            null,
            null
          ],
          "target": 7,
          "left": 0,
          "right": 6,
          "result": 3
        },
        "changed": [],
        "stdout": "3\n"
      },
      {
        "step": 24,
        "line": 27,
        "event": "return",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {},
            "returnValue": 0
          }
        ],
        "variables": {
          "n": 7,
          "arr": [
            1,
            3,
            5,
            7,
            9,
            11,
            13,
            null,
            null,
            null
          ],
          "target": 7,
          "left": 0,
          "right": 6,
          "result": 3
        },
        "changed": [],
        "stdout": "3\n"
      }
    ],
    "stdout": "3\n",
    "stepCount": 25,
    "executionTimeMs": 4,
    "isDemo": true,
    "sandboxWarning": "Dữ liệu mô phỏng từ lần chạy C++ thật (Chế độ xem trước GitHub Pages)"
  },
  "bubble-sort": {
    "success": true,
    "trace": [
      {
        "step": 0,
        "line": 4,
        "event": "call",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {},
        "changed": [],
        "stdout": ""
      },
      {
        "step": 1,
        "line": 5,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": null
        },
        "changed": [
          "n"
        ],
        "stdout": ""
      },
      {
        "step": 2,
        "line": 6,
        "event": "stdin",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5
        },
        "changed": [
          "n"
        ],
        "stdout": ""
      },
      {
        "step": 3,
        "line": 7,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5,
          "arr": [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "stdout": ""
      },
      {
        "step": 4,
        "line": 8,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5,
          "arr": [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 5,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 0,
          "n": 5,
          "arr": [
            5,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 0,
          "mode": "write",
          "value": 5
        },
        "stdout": ""
      },
      {
        "step": 6,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 1,
          "n": 5,
          "arr": [
            5,
            3,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 1,
          "mode": "write",
          "value": 3
        },
        "stdout": ""
      },
      {
        "step": 7,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 2,
          "n": 5,
          "arr": [
            5,
            3,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 2,
          "mode": "write",
          "value": 1
        },
        "stdout": ""
      },
      {
        "step": 8,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 3,
          "n": 5,
          "arr": [
            5,
            3,
            1,
            4,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 3,
          "mode": "write",
          "value": 4
        },
        "stdout": ""
      },
      {
        "step": 9,
        "line": 9,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 4,
          "n": 5,
          "arr": [
            5,
            3,
            1,
            4,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 4,
          "mode": "write",
          "value": 2
        },
        "stdout": ""
      },
      {
        "step": 10,
        "line": 11,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5,
          "arr": [
            5,
            3,
            1,
            4,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 11,
        "line": 12,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 0,
          "n": 5,
          "arr": [
            5,
            3,
            1,
            4,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 12,
        "line": 13,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "j": 0,
          "i": 0,
          "n": 5,
          "arr": [
            5,
            3,
            1,
            4,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "compareInfo": {
          "left": "arr[j]",
          "right": "arr[(j + 1)]",
          "leftValue": 5,
          "rightValue": 3,
          "operator": ">",
          "result": true
        },
        "compareAccesses": [
          {
            "array": "arr",
            "index": 0
          },
          {
            "array": "arr",
            "index": 1
          }
        ],
        "stdout": ""
      },
      {
        "step": 13,
        "line": 14,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 5,
          "j": 0,
          "i": 0,
          "n": 5,
          "arr": [
            5,
            3,
            1,
            4,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "temp"
        ],
        "stdout": ""
      },
      {
        "step": 14,
        "line": 15,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 5,
          "j": 0,
          "i": 0,
          "n": 5,
          "arr": [
            3,
            3,
            1,
            4,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 0,
          "mode": "write",
          "value": 3
        },
        "stdout": ""
      },
      {
        "step": 15,
        "line": 16,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 5,
          "j": 0,
          "i": 0,
          "n": 5,
          "arr": [
            3,
            5,
            1,
            4,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 1,
          "mode": "write",
          "value": 5
        },
        "stdout": ""
      },
      {
        "step": 16,
        "line": 13,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "j": 1,
          "i": 0,
          "n": 5,
          "arr": [
            3,
            5,
            1,
            4,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "compareInfo": {
          "left": "arr[j]",
          "right": "arr[(j + 1)]",
          "leftValue": 5,
          "rightValue": 1,
          "operator": ">",
          "result": true
        },
        "compareAccesses": [
          {
            "array": "arr",
            "index": 1
          },
          {
            "array": "arr",
            "index": 2
          }
        ],
        "stdout": ""
      },
      {
        "step": 17,
        "line": 14,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 5,
          "j": 1,
          "i": 0,
          "n": 5,
          "arr": [
            3,
            5,
            1,
            4,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "temp"
        ],
        "stdout": ""
      },
      {
        "step": 18,
        "line": 15,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 5,
          "j": 1,
          "i": 0,
          "n": 5,
          "arr": [
            3,
            1,
            1,
            4,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 1,
          "mode": "write",
          "value": 1
        },
        "stdout": ""
      },
      {
        "step": 19,
        "line": 16,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 5,
          "j": 1,
          "i": 0,
          "n": 5,
          "arr": [
            3,
            1,
            5,
            4,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 2,
          "mode": "write",
          "value": 5
        },
        "stdout": ""
      },
      {
        "step": 20,
        "line": 13,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "j": 2,
          "i": 0,
          "n": 5,
          "arr": [
            3,
            1,
            5,
            4,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "compareInfo": {
          "left": "arr[j]",
          "right": "arr[(j + 1)]",
          "leftValue": 5,
          "rightValue": 4,
          "operator": ">",
          "result": true
        },
        "compareAccesses": [
          {
            "array": "arr",
            "index": 2
          },
          {
            "array": "arr",
            "index": 3
          }
        ],
        "stdout": ""
      },
      {
        "step": 21,
        "line": 14,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 5,
          "j": 2,
          "i": 0,
          "n": 5,
          "arr": [
            3,
            1,
            5,
            4,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "temp"
        ],
        "stdout": ""
      },
      {
        "step": 22,
        "line": 15,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 5,
          "j": 2,
          "i": 0,
          "n": 5,
          "arr": [
            3,
            1,
            4,
            4,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 2,
          "mode": "write",
          "value": 4
        },
        "stdout": ""
      },
      {
        "step": 23,
        "line": 16,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 5,
          "j": 2,
          "i": 0,
          "n": 5,
          "arr": [
            3,
            1,
            4,
            5,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 3,
          "mode": "write",
          "value": 5
        },
        "stdout": ""
      },
      {
        "step": 24,
        "line": 13,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "j": 3,
          "i": 0,
          "n": 5,
          "arr": [
            3,
            1,
            4,
            5,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "compareInfo": {
          "left": "arr[j]",
          "right": "arr[(j + 1)]",
          "leftValue": 5,
          "rightValue": 2,
          "operator": ">",
          "result": true
        },
        "compareAccesses": [
          {
            "array": "arr",
            "index": 3
          },
          {
            "array": "arr",
            "index": 4
          }
        ],
        "stdout": ""
      },
      {
        "step": 25,
        "line": 14,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 5,
          "j": 3,
          "i": 0,
          "n": 5,
          "arr": [
            3,
            1,
            4,
            5,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "temp"
        ],
        "stdout": ""
      },
      {
        "step": 26,
        "line": 15,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 5,
          "j": 3,
          "i": 0,
          "n": 5,
          "arr": [
            3,
            1,
            4,
            2,
            2,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 3,
          "mode": "write",
          "value": 2
        },
        "stdout": ""
      },
      {
        "step": 27,
        "line": 16,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 5,
          "j": 3,
          "i": 0,
          "n": 5,
          "arr": [
            3,
            1,
            4,
            2,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 4,
          "mode": "write",
          "value": 5
        },
        "stdout": ""
      },
      {
        "step": 28,
        "line": 12,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 1,
          "n": 5,
          "arr": [
            3,
            1,
            4,
            2,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 29,
        "line": 13,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "j": 0,
          "i": 1,
          "n": 5,
          "arr": [
            3,
            1,
            4,
            2,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "compareInfo": {
          "left": "arr[j]",
          "right": "arr[(j + 1)]",
          "leftValue": 3,
          "rightValue": 1,
          "operator": ">",
          "result": true
        },
        "compareAccesses": [
          {
            "array": "arr",
            "index": 0
          },
          {
            "array": "arr",
            "index": 1
          }
        ],
        "stdout": ""
      },
      {
        "step": 30,
        "line": 14,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 3,
          "j": 0,
          "i": 1,
          "n": 5,
          "arr": [
            3,
            1,
            4,
            2,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "temp"
        ],
        "stdout": ""
      },
      {
        "step": 31,
        "line": 15,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 3,
          "j": 0,
          "i": 1,
          "n": 5,
          "arr": [
            1,
            1,
            4,
            2,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 0,
          "mode": "write",
          "value": 1
        },
        "stdout": ""
      },
      {
        "step": 32,
        "line": 16,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 3,
          "j": 0,
          "i": 1,
          "n": 5,
          "arr": [
            1,
            3,
            4,
            2,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 1,
          "mode": "write",
          "value": 3
        },
        "stdout": ""
      },
      {
        "step": 33,
        "line": 13,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "j": 1,
          "i": 1,
          "n": 5,
          "arr": [
            1,
            3,
            4,
            2,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "compareInfo": {
          "left": "arr[j]",
          "right": "arr[(j + 1)]",
          "leftValue": 3,
          "rightValue": 4,
          "operator": ">",
          "result": false
        },
        "compareAccesses": [
          {
            "array": "arr",
            "index": 1
          },
          {
            "array": "arr",
            "index": 2
          }
        ],
        "stdout": ""
      },
      {
        "step": 34,
        "line": 13,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "j": 2,
          "i": 1,
          "n": 5,
          "arr": [
            1,
            3,
            4,
            2,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "compareInfo": {
          "left": "arr[j]",
          "right": "arr[(j + 1)]",
          "leftValue": 4,
          "rightValue": 2,
          "operator": ">",
          "result": true
        },
        "compareAccesses": [
          {
            "array": "arr",
            "index": 2
          },
          {
            "array": "arr",
            "index": 3
          }
        ],
        "stdout": ""
      },
      {
        "step": 35,
        "line": 14,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 4,
          "j": 2,
          "i": 1,
          "n": 5,
          "arr": [
            1,
            3,
            4,
            2,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "temp"
        ],
        "stdout": ""
      },
      {
        "step": 36,
        "line": 15,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 4,
          "j": 2,
          "i": 1,
          "n": 5,
          "arr": [
            1,
            3,
            2,
            2,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 2,
          "mode": "write",
          "value": 2
        },
        "stdout": ""
      },
      {
        "step": 37,
        "line": 16,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 4,
          "j": 2,
          "i": 1,
          "n": 5,
          "arr": [
            1,
            3,
            2,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 3,
          "mode": "write",
          "value": 4
        },
        "stdout": ""
      },
      {
        "step": 38,
        "line": 12,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 2,
          "n": 5,
          "arr": [
            1,
            3,
            2,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 39,
        "line": 13,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "j": 0,
          "i": 2,
          "n": 5,
          "arr": [
            1,
            3,
            2,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "compareInfo": {
          "left": "arr[j]",
          "right": "arr[(j + 1)]",
          "leftValue": 1,
          "rightValue": 3,
          "operator": ">",
          "result": false
        },
        "compareAccesses": [
          {
            "array": "arr",
            "index": 0
          },
          {
            "array": "arr",
            "index": 1
          }
        ],
        "stdout": ""
      },
      {
        "step": 40,
        "line": 13,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "j": 1,
          "i": 2,
          "n": 5,
          "arr": [
            1,
            3,
            2,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "compareInfo": {
          "left": "arr[j]",
          "right": "arr[(j + 1)]",
          "leftValue": 3,
          "rightValue": 2,
          "operator": ">",
          "result": true
        },
        "compareAccesses": [
          {
            "array": "arr",
            "index": 1
          },
          {
            "array": "arr",
            "index": 2
          }
        ],
        "stdout": ""
      },
      {
        "step": 41,
        "line": 14,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 3,
          "j": 1,
          "i": 2,
          "n": 5,
          "arr": [
            1,
            3,
            2,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "temp"
        ],
        "stdout": ""
      },
      {
        "step": 42,
        "line": 15,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 3,
          "j": 1,
          "i": 2,
          "n": 5,
          "arr": [
            1,
            2,
            2,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 1,
          "mode": "write",
          "value": 2
        },
        "stdout": ""
      },
      {
        "step": 43,
        "line": 16,
        "event": "write",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "temp": 3,
          "j": 1,
          "i": 2,
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [
          "arr"
        ],
        "arrayAccess": {
          "array": "arr",
          "index": 2,
          "mode": "write",
          "value": 3
        },
        "stdout": ""
      },
      {
        "step": 44,
        "line": 12,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 3,
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 45,
        "line": 13,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "j": 0,
          "i": 3,
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "compareInfo": {
          "left": "arr[j]",
          "right": "arr[(j + 1)]",
          "leftValue": 1,
          "rightValue": 2,
          "operator": ">",
          "result": false
        },
        "compareAccesses": [
          {
            "array": "arr",
            "index": 0
          },
          {
            "array": "arr",
            "index": 1
          }
        ],
        "stdout": ""
      },
      {
        "step": 46,
        "line": 20,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 47,
        "line": 21,
        "event": "stdout",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 0,
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": "1 "
      },
      {
        "step": 48,
        "line": 21,
        "event": "stdout",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 1,
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": "1 2 "
      },
      {
        "step": 49,
        "line": 21,
        "event": "stdout",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 2,
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": "1 2 3 "
      },
      {
        "step": 50,
        "line": 21,
        "event": "stdout",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 3,
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": "1 2 3 4 "
      },
      {
        "step": 51,
        "line": 21,
        "event": "stdout",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "i": 4,
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": "1 2 3 4 5 "
      },
      {
        "step": 52,
        "line": 23,
        "event": "stdout",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": "1 2 3 4 5 \n"
      },
      {
        "step": 53,
        "line": 24,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": "1 2 3 4 5 \n"
      },
      {
        "step": 54,
        "line": 24,
        "event": "return",
        "callStack": [
          {
            "func": "main",
            "line": 4,
            "id": 1,
            "params": {},
            "returnValue": 0
          }
        ],
        "variables": {
          "n": 5,
          "arr": [
            1,
            2,
            3,
            4,
            5,
            null,
            null,
            null,
            null,
            null
          ]
        },
        "changed": [],
        "stdout": "1 2 3 4 5 \n"
      }
    ],
    "stdout": "1 2 3 4 5 \n",
    "stepCount": 55,
    "executionTimeMs": 4,
    "isDemo": true,
    "sandboxWarning": "Dữ liệu mô phỏng từ lần chạy C++ thật (Chế độ xem trước GitHub Pages)"
  },
  "factorial": {
    "success": true,
    "trace": [
      {
        "step": 0,
        "line": 11,
        "event": "call",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {},
        "changed": [],
        "stdout": ""
      },
      {
        "step": 1,
        "line": 12,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": null
        },
        "changed": [
          "n"
        ],
        "stdout": ""
      },
      {
        "step": 2,
        "line": 13,
        "event": "stdin",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5
        },
        "changed": [
          "n"
        ],
        "stdout": ""
      },
      {
        "step": 3,
        "line": 4,
        "event": "call",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          }
        ],
        "variables": {
          "n": 5
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 4,
        "line": 5,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          }
        ],
        "variables": {
          "n": 5
        },
        "changed": [],
        "compareInfo": {
          "left": "n",
          "right": "1",
          "leftValue": 5,
          "rightValue": 1,
          "operator": "<=",
          "result": false
        },
        "compareAccesses": [],
        "stdout": ""
      },
      {
        "step": 5,
        "line": 8,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          }
        ],
        "variables": {
          "n": 5
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 6,
        "line": 4,
        "event": "call",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 3,
            "params": {
              "n": 4
            }
          }
        ],
        "variables": {
          "n": 4
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 7,
        "line": 5,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 3,
            "params": {
              "n": 4
            }
          }
        ],
        "variables": {
          "n": 4
        },
        "changed": [],
        "compareInfo": {
          "left": "n",
          "right": "1",
          "leftValue": 4,
          "rightValue": 1,
          "operator": "<=",
          "result": false
        },
        "compareAccesses": [],
        "stdout": ""
      },
      {
        "step": 8,
        "line": 8,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 3,
            "params": {
              "n": 4
            }
          }
        ],
        "variables": {
          "n": 4
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 9,
        "line": 4,
        "event": "call",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 3,
            "params": {
              "n": 4
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 4,
            "params": {
              "n": 3
            }
          }
        ],
        "variables": {
          "n": 3
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 10,
        "line": 5,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 3,
            "params": {
              "n": 4
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 4,
            "params": {
              "n": 3
            }
          }
        ],
        "variables": {
          "n": 3
        },
        "changed": [],
        "compareInfo": {
          "left": "n",
          "right": "1",
          "leftValue": 3,
          "rightValue": 1,
          "operator": "<=",
          "result": false
        },
        "compareAccesses": [],
        "stdout": ""
      },
      {
        "step": 11,
        "line": 8,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 3,
            "params": {
              "n": 4
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 4,
            "params": {
              "n": 3
            }
          }
        ],
        "variables": {
          "n": 3
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 12,
        "line": 4,
        "event": "call",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 3,
            "params": {
              "n": 4
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 4,
            "params": {
              "n": 3
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 5,
            "params": {
              "n": 2
            }
          }
        ],
        "variables": {
          "n": 2
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 13,
        "line": 5,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 3,
            "params": {
              "n": 4
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 4,
            "params": {
              "n": 3
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 5,
            "params": {
              "n": 2
            }
          }
        ],
        "variables": {
          "n": 2
        },
        "changed": [],
        "compareInfo": {
          "left": "n",
          "right": "1",
          "leftValue": 2,
          "rightValue": 1,
          "operator": "<=",
          "result": false
        },
        "compareAccesses": [],
        "stdout": ""
      },
      {
        "step": 14,
        "line": 8,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 3,
            "params": {
              "n": 4
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 4,
            "params": {
              "n": 3
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 5,
            "params": {
              "n": 2
            }
          }
        ],
        "variables": {
          "n": 2
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 15,
        "line": 4,
        "event": "call",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 3,
            "params": {
              "n": 4
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 4,
            "params": {
              "n": 3
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 5,
            "params": {
              "n": 2
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 6,
            "params": {
              "n": 1
            }
          }
        ],
        "variables": {
          "n": 1
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 16,
        "line": 5,
        "event": "compare",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 3,
            "params": {
              "n": 4
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 4,
            "params": {
              "n": 3
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 5,
            "params": {
              "n": 2
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 6,
            "params": {
              "n": 1
            }
          }
        ],
        "variables": {
          "n": 1
        },
        "changed": [],
        "compareInfo": {
          "left": "n",
          "right": "1",
          "leftValue": 1,
          "rightValue": 1,
          "operator": "<=",
          "result": true
        },
        "compareAccesses": [],
        "stdout": ""
      },
      {
        "step": 17,
        "line": 6,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 3,
            "params": {
              "n": 4
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 4,
            "params": {
              "n": 3
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 5,
            "params": {
              "n": 2
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 6,
            "params": {
              "n": 1
            }
          }
        ],
        "variables": {
          "n": 1
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 18,
        "line": 6,
        "event": "return",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 3,
            "params": {
              "n": 4
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 4,
            "params": {
              "n": 3
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 5,
            "params": {
              "n": 2
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 6,
            "params": {
              "n": 1
            },
            "returnValue": 1
          }
        ],
        "variables": {
          "n": 1
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 19,
        "line": 8,
        "event": "return",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 3,
            "params": {
              "n": 4
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 4,
            "params": {
              "n": 3
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 5,
            "params": {
              "n": 2
            },
            "returnValue": 2
          }
        ],
        "variables": {
          "n": 2
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 20,
        "line": 8,
        "event": "return",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 3,
            "params": {
              "n": 4
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 4,
            "params": {
              "n": 3
            },
            "returnValue": 6
          }
        ],
        "variables": {
          "n": 3
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 21,
        "line": 8,
        "event": "return",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            }
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 3,
            "params": {
              "n": 4
            },
            "returnValue": 24
          }
        ],
        "variables": {
          "n": 4
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 22,
        "line": 8,
        "event": "return",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          },
          {
            "func": "factorial",
            "line": 4,
            "id": 2,
            "params": {
              "n": 5
            },
            "returnValue": 120
          }
        ],
        "variables": {
          "n": 5
        },
        "changed": [],
        "stdout": ""
      },
      {
        "step": 23,
        "line": 14,
        "event": "vardecl",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5,
          "result": 120
        },
        "changed": [
          "result"
        ],
        "stdout": ""
      },
      {
        "step": 24,
        "line": 15,
        "event": "stdout",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5,
          "result": 120
        },
        "changed": [],
        "stdout": "120\n"
      },
      {
        "step": 25,
        "line": 16,
        "event": "line",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {}
          }
        ],
        "variables": {
          "n": 5,
          "result": 120
        },
        "changed": [],
        "stdout": "120\n"
      },
      {
        "step": 26,
        "line": 16,
        "event": "return",
        "callStack": [
          {
            "func": "main",
            "line": 11,
            "id": 1,
            "params": {},
            "returnValue": 0
          }
        ],
        "variables": {
          "n": 5,
          "result": 120
        },
        "changed": [],
        "stdout": "120\n"
      }
    ],
    "stdout": "120\n",
    "stepCount": 27,
    "executionTimeMs": 4,
    "isDemo": true,
    "sandboxWarning": "Dữ liệu mô phỏng từ lần chạy C++ thật (Chế độ xem trước GitHub Pages)"
  }
};
export function getFallbackDemoTrace(code: string, stdin: string): Partial<ExecuteResponse> | null {
  const sample = SAMPLES.find(s => s.code === code && s.stdin === stdin);
  return sample ? DEMO_TRACES[sample.id] || null : null;
}
